# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import DataCollector_pb2 as DataCollector__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in DataCollector_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DataCollectorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddAirport = channel.unary_unary(
                '/DataCollectorService/AddAirport',
                request_serializer=DataCollector__pb2.AirportRequest.SerializeToString,
                response_deserializer=DataCollector__pb2.GenericResponse.FromString,
                _registered_method=True)
        self.RemoveAirport = channel.unary_unary(
                '/DataCollectorService/RemoveAirport',
                request_serializer=DataCollector__pb2.AirportRequest.SerializeToString,
                response_deserializer=DataCollector__pb2.GenericResponse.FromString,
                _registered_method=True)
        self.ListAirports = channel.unary_unary(
                '/DataCollectorService/ListAirports',
                request_serializer=DataCollector__pb2.AirportListRequest.SerializeToString,
                response_deserializer=DataCollector__pb2.AirportListResponse.FromString,
                _registered_method=True)
        self.RefreshFlights = channel.unary_unary(
                '/DataCollectorService/RefreshFlights',
                request_serializer=DataCollector__pb2.RefreshRequest.SerializeToString,
                response_deserializer=DataCollector__pb2.RefreshResponse.FromString,
                _registered_method=True)
        self.ListFlights = channel.unary_unary(
                '/DataCollectorService/ListFlights',
                request_serializer=DataCollector__pb2.FlightsRequest.SerializeToString,
                response_deserializer=DataCollector__pb2.FlightsResponse.FromString,
                _registered_method=True)
        self.AverageFlightsPerDay = channel.unary_unary(
                '/DataCollectorService/AverageFlightsPerDay',
                request_serializer=DataCollector__pb2.DaysRequest.SerializeToString,
                response_deserializer=DataCollector__pb2.DaysResponse.FromString,
                _registered_method=True)
        self.LastFlights = channel.unary_unary(
                '/DataCollectorService/LastFlights',
                request_serializer=DataCollector__pb2.LastFlightsRequest.SerializeToString,
                response_deserializer=DataCollector__pb2.LastFlightsResponse.FromString,
                _registered_method=True)
        self.UpdateAirportThresholds = channel.unary_unary(
                '/DataCollectorService/UpdateAirportThresholds',
                request_serializer=DataCollector__pb2.AirportThresholdsRequest.SerializeToString,
                response_deserializer=DataCollector__pb2.AirportThresholdsResponse.FromString,
                _registered_method=True)


class DataCollectorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddAirport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveAirport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAirports(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefreshFlights(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFlights(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AverageFlightsPerDay(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LastFlights(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateAirportThresholds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataCollectorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddAirport': grpc.unary_unary_rpc_method_handler(
                    servicer.AddAirport,
                    request_deserializer=DataCollector__pb2.AirportRequest.FromString,
                    response_serializer=DataCollector__pb2.GenericResponse.SerializeToString,
            ),
            'RemoveAirport': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveAirport,
                    request_deserializer=DataCollector__pb2.AirportRequest.FromString,
                    response_serializer=DataCollector__pb2.GenericResponse.SerializeToString,
            ),
            'ListAirports': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAirports,
                    request_deserializer=DataCollector__pb2.AirportListRequest.FromString,
                    response_serializer=DataCollector__pb2.AirportListResponse.SerializeToString,
            ),
            'RefreshFlights': grpc.unary_unary_rpc_method_handler(
                    servicer.RefreshFlights,
                    request_deserializer=DataCollector__pb2.RefreshRequest.FromString,
                    response_serializer=DataCollector__pb2.RefreshResponse.SerializeToString,
            ),
            'ListFlights': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFlights,
                    request_deserializer=DataCollector__pb2.FlightsRequest.FromString,
                    response_serializer=DataCollector__pb2.FlightsResponse.SerializeToString,
            ),
            'AverageFlightsPerDay': grpc.unary_unary_rpc_method_handler(
                    servicer.AverageFlightsPerDay,
                    request_deserializer=DataCollector__pb2.DaysRequest.FromString,
                    response_serializer=DataCollector__pb2.DaysResponse.SerializeToString,
            ),
            'LastFlights': grpc.unary_unary_rpc_method_handler(
                    servicer.LastFlights,
                    request_deserializer=DataCollector__pb2.LastFlightsRequest.FromString,
                    response_serializer=DataCollector__pb2.LastFlightsResponse.SerializeToString,
            ),
            'UpdateAirportThresholds': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateAirportThresholds,
                    request_deserializer=DataCollector__pb2.AirportThresholdsRequest.FromString,
                    response_serializer=DataCollector__pb2.AirportThresholdsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DataCollectorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('DataCollectorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DataCollectorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddAirport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DataCollectorService/AddAirport',
            DataCollector__pb2.AirportRequest.SerializeToString,
            DataCollector__pb2.GenericResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveAirport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DataCollectorService/RemoveAirport',
            DataCollector__pb2.AirportRequest.SerializeToString,
            DataCollector__pb2.GenericResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAirports(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DataCollectorService/ListAirports',
            DataCollector__pb2.AirportListRequest.SerializeToString,
            DataCollector__pb2.AirportListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefreshFlights(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DataCollectorService/RefreshFlights',
            DataCollector__pb2.RefreshRequest.SerializeToString,
            DataCollector__pb2.RefreshResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListFlights(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DataCollectorService/ListFlights',
            DataCollector__pb2.FlightsRequest.SerializeToString,
            DataCollector__pb2.FlightsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AverageFlightsPerDay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DataCollectorService/AverageFlightsPerDay',
            DataCollector__pb2.DaysRequest.SerializeToString,
            DataCollector__pb2.DaysResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LastFlights(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DataCollectorService/LastFlights',
            DataCollector__pb2.LastFlightsRequest.SerializeToString,
            DataCollector__pb2.LastFlightsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateAirportThresholds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DataCollectorService/UpdateAirportThresholds',
            DataCollector__pb2.AirportThresholdsRequest.SerializeToString,
            DataCollector__pb2.AirportThresholdsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
