# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: DataCollector.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'DataCollector.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x44\x61taCollector.proto\"-\n\x0e\x41irportRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\"#\n\x12\x41irportListRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"$\n\x13\x41irportListResponse\x12\r\n\x05\x63odes\x18\x01 \x03(\t\"\x1f\n\x0eRefreshRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\";\n\x0fRefreshResponse\x12\x17\n\x0frefreshed_count\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"0\n\x0e\x46lightsRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x0f\n\x07\x61irport\x18\x02 \x01(\t\"\xa1\x01\n\x06\x46light\x12\x0e\n\x06icao24\x18\x01 \x01(\t\x12\x10\n\x08\x63\x61llsign\x18\x02 \x01(\t\x12\x19\n\x11\x64\x65parture_airport\x18\x03 \x01(\t\x12\x17\n\x0f\x61rrival_airport\x18\x04 \x01(\t\x12\x16\n\x0e\x64\x65parture_time\x18\x05 \x01(\x03\x12\x14\n\x0c\x61rrival_time\x18\x06 \x01(\x03\x12\x13\n\x0b\x66light_type\x18\x07 \x01(\t\"+\n\x0f\x46lightsResponse\x12\x18\n\x07\x66lights\x18\x01 \x03(\x0b\x32\x07.Flight\"2\n\x0fGenericResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t2\x9d\x02\n\x14\x44\x61taCollectorService\x12/\n\nAddAirport\x12\x0f.AirportRequest\x1a\x10.GenericResponse\x12\x32\n\rRemoveAirport\x12\x0f.AirportRequest\x1a\x10.GenericResponse\x12\x39\n\x0cListAirports\x12\x13.AirportListRequest\x1a\x14.AirportListResponse\x12\x33\n\x0eRefreshFlights\x12\x0f.RefreshRequest\x1a\x10.RefreshResponse\x12\x30\n\x0bListFlights\x12\x0f.FlightsRequest\x1a\x10.FlightsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'DataCollector_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AIRPORTREQUEST']._serialized_start=23
  _globals['_AIRPORTREQUEST']._serialized_end=68
  _globals['_AIRPORTLISTREQUEST']._serialized_start=70
  _globals['_AIRPORTLISTREQUEST']._serialized_end=105
  _globals['_AIRPORTLISTRESPONSE']._serialized_start=107
  _globals['_AIRPORTLISTRESPONSE']._serialized_end=143
  _globals['_REFRESHREQUEST']._serialized_start=145
  _globals['_REFRESHREQUEST']._serialized_end=176
  _globals['_REFRESHRESPONSE']._serialized_start=178
  _globals['_REFRESHRESPONSE']._serialized_end=237
  _globals['_FLIGHTSREQUEST']._serialized_start=239
  _globals['_FLIGHTSREQUEST']._serialized_end=287
  _globals['_FLIGHT']._serialized_start=290
  _globals['_FLIGHT']._serialized_end=451
  _globals['_FLIGHTSRESPONSE']._serialized_start=453
  _globals['_FLIGHTSRESPONSE']._serialized_end=496
  _globals['_GENERICRESPONSE']._serialized_start=498
  _globals['_GENERICRESPONSE']._serialized_end=548
  _globals['_DATACOLLECTORSERVICE']._serialized_start=551
  _globals['_DATACOLLECTORSERVICE']._serialized_end=836
# @@protoc_insertion_point(module_scope)
